import  { StyleSheet } from 'react-native'

export const loginStyles = StyleSheet.create({
    Login: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      width: 375,
      height: 812,
      paddingLeft: 18,
      paddingRight: 17,
      paddingTop: 29,
      paddingBottom: 17,
      borderRadius: 15,
      backgroundColor: "rgba(242,247,255,1)",
    },
    Group971: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
      height: "100%",
    },
    Image1: {
      width: 328,
      height: 191,
    },
    Group598: {
      width: "100%",
      height: 536,
      paddingLeft: 2,
      paddingRight: 3,
      paddingTop: 40,
      paddingBottom: 47,
      borderRadius: 20,
      
      backgroundColor: "rgba(255,255,255,1)",
    },
    Component1: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      width: "100%",
      height: "100%",
      
    },
    Group351: {
      position: "absolute",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      width: 318,
      height: 416,
      
    },
    Button: {
        width: "100%",
        height: 58,
        paddingRight: 10,
        
      },
      Group081: {
        width: 308,
        height: "100%",
        paddingLeft: 201,
        paddingRight: 32,
        paddingTop: 17,
        paddingBottom: 21,
        borderRadius: 40,
        
        backgroundColor: "rgba(217,217,217,1)",
      },
      SignUp: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        color: "rgba(13,13,13,1)",
        fontSize: 20,
        lineHeight: 20,
        fontFamily: "Inter, sans-serif",
        fontWeight: "700",
        textAlign: "center",
      },
      Bienvenidos: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        color: "rgba(0,0,0,1)",
        fontSize: 24,
        lineHeight: 24,
        fontFamily: "Inter, sans-serif",
        fontWeight: "700",
        textAlign: "center",
      },
      Input1: {
        width: "100%",
        height: 34,
        paddingRight: 206,
        paddingTop: 8,
        paddingBottom: 8,
        
      },
      EMail: {
        color: "rgba(154,154,154,1)",
        fontSize: 18,
        lineHeight: 18,
        fontFamily: "Inter, sans-serif",
        fontWeight: "500",
      },
      Input2: {
        width: "100%",
        height: 34,
        paddingRight: 177,
        paddingTop: 8,
        paddingBottom: 8,
        
      },
      Password: {
        color: "rgba(154,154,154,1)",
        fontSize: 18,
        lineHeight: 18,
        fontFamily: "Inter, sans-serif",
        fontWeight: "500",
      },
      Button1: {
        width: "100%",
        height: 54,
        paddingLeft: 60,
        paddingRight: 59,
        paddingTop: 15,
        paddingBottom: 19,
        borderRadius: 32,
        
        backgroundColor:
          " linear-gradient(90deg, rgba(0,198,251,1) 0%, rgba(0,91,234,1) 100%) ",
      },
      LogIn: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        color: "rgba(255,255,255,1)",
        fontSize: 20,
        lineHeight: 20,
        fontFamily: "Inter, sans-serif",
        fontWeight: "700",
        textAlign: "center",
      },
      OlivdasteTuContraseA: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        color: "rgba(0,0,0,1)",
        fontSize: 18,
        lineHeight: 18,
        fontFamily: "Inder, sans-serif",
        fontWeight: "400",
        textAlign: "center",
      },
      Button2: {
        position: "absolute",
        left: 9,
        width: 168,
        height: 58,
        paddingLeft: 49,
        paddingRight: 60,
        paddingTop: 17,
        paddingBottom: 21,
        borderRadius: 32,
        
        backgroundColor:
          " linear-gradient(90deg, rgba(0,198,251,1) 0%, rgba(0,91,234,1) 100%) ",
      },
      LogIn1: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        color: "rgba(255,255,255,1)",
        fontSize: 20,
        lineHeight: 20,
        fontFamily: "Inter, sans-serif",
        fontWeight: "700",
        textAlign: "center",
      },
    })